CREATE TABLE IF NOT EXISTS project (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT 'Project Name',
    description TEXT COMMENT 'Project Description',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS metric_def (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE COMMENT 'Metric Name',
    direction VARCHAR(10) NOT NULL COMMENT 'Optimization Direction: MAX or MIN',
    description VARCHAR(255) COMMENT 'Metric Description',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tag (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE COMMENT 'Tag Name',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL COMMENT 'Project ID',
    name VARCHAR(255) NOT NULL COMMENT 'Run Name',
    status VARCHAR(50) DEFAULT 'RUNNING' COMMENT 'Status: RUNNING, FINISHED, FAILED',
    model_name VARCHAR(255) COMMENT 'Model Architecture Name',
    dataset_name VARCHAR(255) COMMENT 'Dataset Name',
    optimizer VARCHAR(50) COMMENT 'Optimizer Name',
    lr DOUBLE COMMENT 'Learning Rate',
    batch_size INT COMMENT 'Batch Size',
    epochs INT COMMENT 'Total Epochs',
    seed INT COMMENT 'Random Seed',
    note TEXT COMMENT 'Run Note',
    start_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Run Start Time',
    end_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Run End Time',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_project_id (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS run_metric (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT NOT NULL,
    metric_def_id BIGINT NOT NULL,
    value DOUBLE NOT NULL,
    UNIQUE KEY uk_run_metric (run_id, metric_def_id),
    INDEX idx_run_id (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS run_tag (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    UNIQUE KEY uk_run_tag (run_id, tag_id),
    INDEX idx_run_id (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
